services:
    kernel.listener.request_listener:
        class:     TeaAndCode\APIBundle\EventListener\KernelListener
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
        
    
    post_persist_listener:
        class:     TeaAndCode\APIBundle\EventListener\PersistListener
        arguments: [ @doctrine, @service_container ]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
        
    
    tea_and_code.api_bundle.handler.login_failure:
        class:     TeaAndCode\APIBundle\Handler\LoginFailure
        arguments: [ @doctrine, @router, @service_container ]
        tags:
            - { name: monolog.logger, event: security }
        
    
    tea_and_code.api_bundle.handler.login_success:
        class:     TeaAndCode\APIBundle\Handler\LoginSuccess
        arguments: [ @doctrine, @router, @service_container ]
        tags:
            - { name: monolog.logger, event: security }
        
    
