services:
    tea_and_code.api_bundle.handler.login_success:
        class:     TeaAndCode\APIBundle\Handler\LoginSuccess
        arguments: [ @doctrine, @router, @service_container ]
        tags:
            - { name: monolog.logger, event: security }
    persist_listener:
        class:     TeaAndCode\APIBundle\EventListener\PersistListener
        arguments: [ @doctrine, @service_container ]
        tags:
            - { name: doctrine.event_listener, event: postPersist }